(() => {
  'use strict';
  const canvas = document.getElementById('world'), ctx = canvas.getContext('2d');
  const $ = id => document.getElementById(id);
  const el = {speed:$('speed'),alt:$('altitude'),heading:$('heading'),direction:$('direction'),vspeed:$('vspeed'),throttle:$('throttle'),speedBar:$('speedBar'),altBar:$('altBar'),vsiBar:$('vsiBar'),throttleBar:$('throttleBar'),phase:$('phasePill'),title:$('missionTitle'),text:$('missionText'),progress:$('missionProgress'),hint:$('hint'),message:$('message'),pause:$('pauseOverlay'),fps:$('fps'),route:$('routeProgress'),plane:$('planeIcon'),routePhase:$('routePhase'),remaining:$('distanceRemaining'),n1:$('n1'),flaps:$('flaps'),gear:$('gear'),gearLight:$('gearLight'),fuel:$('fuel'),flight:$('flightNumber'),origin:$('originCode'),originCity:$('originCity'),dest:$('destCode'),destCity:$('destCity'),wps:[$('wp1'),$('wp2'),$('wp3')]};
  let W=0,H=0,dpr=1,last=performance.now(),paused=false,sound=false,audio=null,msgTimer=0,fpsSmooth=60;
  const keys={}, touch={pitch:0,roll:0,yaw:0,up:false,down:false};
  const state={throttle:0,speed:0,altitude:0,heading:280,pitch:0,roll:0,yaw:0,vSpeed:0,distance:0,phase:'PREFLIGHT',landed:false,crashed:false,time:0,fuel:8.4};
  const routes=[
    {o:'VIDP',oc:'DELHI',d:'KJFK',dc:'NEW YORK',type:'INTERNATIONAL',nm:6350,dep:'29R',arr:'22L',hdg:290,w:['KABIM','TULSI','CAMRN']},
    {o:'VABB',oc:'MUMBAI',d:'KSFO',dc:'SAN FRANCISCO',type:'INTERNATIONAL',nm:7300,dep:'27',arr:'28R',hdg:274,w:['RASKI','GULUM','PORTE']},
    {o:'EGLL',oc:'LONDON',d:'WSSS',dc:'SINGAPORE',type:'INTERNATIONAL',nm:5880,dep:'27R',arr:'20C',hdg:112,w:['DVR','KARLI','PASPU']},
    {o:'RJTT',oc:'TOKYO',d:'YSSY',dc:'SYDNEY',type:'INTERNATIONAL',nm:4220,dep:'16R',arr:'34L',hdg:168,w:['KAIHO','AKMAL','RIVET']},
    {o:'OMDB',oc:'DUBAI',d:'LFPG',dc:'PARIS',type:'INTERNATIONAL',nm:2820,dep:'30R',arr:'26L',hdg:304,w:['DAVMO','NISVA','OKIPA']},
    {o:'KJFK',oc:'NEW YORK',d:'KLAX',dc:'LOS ANGELES',type:'DOMESTIC',nm:2140,dep:'31L',arr:'25L',hdg:274,w:['GREKI','J80','CIVET']},
    {o:'VIDP',oc:'DELHI',d:'VOBL',dc:'BENGALURU',type:'DOMESTIC',nm:920,dep:'29R',arr:'09L',hdg:171,w:['GURGA','BUBKO','BIA']},
    {o:'YMML',oc:'MELBOURNE',d:'YBBN',dc:'BRISBANE',type:'DOMESTIC',nm:750,dep:'27',arr:'19L',hdg:25,w:['DOSEL','WOL','SMOKA']},
    {o:'KDEN',oc:'DENVER',d:'KORD',dc:'CHICAGO',type:'DOMESTIC',nm:770,dep:'34L',arr:'28C',hdg:64,w:['YAMMI','MCK','BENKY']},
    {o:'KORD',oc:'CHICAGO',d:'KMIA',dc:'MIAMI',type:'DOMESTIC',nm:1040,dep:'28R',arr:'09',hdg:158,w:['BACEN','ATL','FLIPR']},
    {o:'KMIA',oc:'MIAMI',d:'KDEN',dc:'DENVER',type:'DOMESTIC',nm:1480,dep:'08R',arr:'35R',hdg:304,w:['DEEDS','CEW','RAMMS']}
  ];
  let routeIndex=-1,currentRoute=routes[0];
  function chooseRoute(){let next;do{next=Math.floor(Math.random()*routes.length)}while(routes.length>1&&next===routeIndex);routeIndex=next;currentRoute=routes[next];state.heading=currentRoute.hdg;el.flight.textContent=`DATTA AIR ${100+Math.floor(Math.random()*890)} · ${currentRoute.type}`;el.origin.textContent=currentRoute.o;el.originCity.textContent=currentRoute.oc;el.dest.textContent=currentRoute.d;el.destCity.textContent=currentRoute.dc;el.wps.forEach((node,i)=>node.textContent=currentRoute.w[i])}
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), lerp=(a,b,t)=>a+(b-a)*t;
  const airportProfiles={VIDP:['haze',['#776a5d','#b9aa8b','#dcc69b','#6d6744'],2],VABB:['coast',['#365d76','#92afb8','#e1bd8d','#345444'],1],KSFO:['bay',['#395a70','#9eb1b4','#d8c29c','#39574b'],2],KJFK:['urban',['#2e4c67','#8ea3ae','#c9b48e','#34433c'],0],VOBL:['plateau',['#45687a','#a5b8b4','#d7c89f','#446044'],1],EGLL:['flat',['#394b5e','#87929c','#c1b29a','#41513b'],0],WSSS:['tropical',['#315f71','#8eb8b7','#d9c18c','#22573e'],2],RJTT:['bay',['#355875','#94aeb8','#dcc49d','#385347'],1],YSSY:['harbor',['#365f79','#9cb6bc','#dfc39c','#315446'],2],OMDB:['desert',['#66526a','#c38d79','#e9bc7d','#6c5b37'],0],LFPG:['flat',['#38546b','#96a7ad','#cfbea1','#3c5039'],1],KLAX:['urban',['#40556b','#9fa7aa','#d4b28b','#5c543a'],2],YMML:['flat',['#405b70','#9eafb0','#d5c39c','#3f583e'],1],YBBN:['tropical',['#3d6a7c','#9dbdb9','#dcc696','#315c3e'],2],KDEN:['mountain',['#355472','#94aab3','#d9bd91','#526044'],2],KORD:['urban',['#324b62','#879aa5','#c8b695','#3e4d38'],0],KMIA:['tropical',['#32748a','#a2ceca','#efd19a','#2d6a50'],1]};
  function airportVisual(){const landing=state.phase==='APPROACH'||state.phase==='FINAL'||state.phase==='ARRIVED',code=landing?currentRoute.d:currentRoute.o,seed=[...code].reduce((n,c)=>n*31+c.charCodeAt(0),7),profile=airportProfiles[code]||['flat',['#405a6b','#a9b7b7','#d9c49b','#263b31'],seed%3];return{code,seed,terrain:profile[0],colors:profile[1],side:seed%2?1:-1,layout:profile[2],towers:2+seed%4,dusk:seed%4===3}}
  function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)} addEventListener('resize',resize);resize();
  addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyS','KeyA','KeyD','Space','KeyP','KeyR'].includes(e.code))e.preventDefault();keys[e.code]=true;if((e.code==='Space'||e.code==='KeyP')&&!e.repeat)togglePause();if(e.code==='KeyR'&&!e.repeat)reset()});
  addEventListener('keyup',e=>keys[e.code]=false);
  function notify(t){el.message.textContent=t;el.message.classList.add('show');clearTimeout(msgTimer);msgTimer=setTimeout(()=>el.message.classList.remove('show'),2200)}
  function reset(){Object.assign(state,{throttle:0,speed:0,altitude:0,pitch:0,roll:0,yaw:0,vSpeed:0,distance:0,phase:'PREFLIGHT',landed:false,crashed:false,time:0,fuel:8.4});chooseRoute();paused=false;el.pause.classList.remove('show');notify(`${currentRoute.o} RUNWAY ${currentRoute.dep} · BOARDING COMPLETE`)}
  function togglePause(){paused=!paused;el.pause.classList.toggle('show',paused);$('pauseBtn').textContent=paused?'RESUME':'PAUSE';if(audio)audio.gain.gain.setTargetAtTime(paused?0:state.throttle*.045,audio.ctx.currentTime,.08)}
  $('pauseBtn').onclick=togglePause;$('resumeBtn').onclick=togglePause;$('resetBtn').onclick=reset;
  $('helpToggle').onclick=()=>{const c=document.querySelector('.controls-card');c.classList.toggle('hidden');$('helpToggle').textContent=c.classList.contains('hidden')?'SHOW CONTROLS':'HIDE CONTROLS'};
  $('soundBtn').onclick=()=>{sound=!sound;$('soundBtn').textContent=sound?'SOUND ON':'SOUND OFF';if(sound&&!audio){const ac=new (window.AudioContext||window.webkitAudioContext)(),osc=ac.createOscillator(),gain=ac.createGain(),filter=ac.createBiquadFilter();osc.type='sawtooth';osc.frequency.value=55;filter.type='lowpass';filter.frequency.value=180;gain.gain.value=0;osc.connect(filter).connect(gain).connect(ac.destination);osc.start();audio={ctx:ac,osc,gain}}};
  function bindHold(btn,name){const set=v=>{touch[name]=v;btn.classList.toggle('active',v)};btn.addEventListener('pointerdown',e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);set(true)});btn.addEventListener('pointerup',()=>set(false));btn.addEventListener('pointercancel',()=>set(false))}
  document.querySelectorAll('[data-control]').forEach(b=>bindHold(b,{throttleUp:'up',throttleDown:'down',yawLeft:'yawL',yawRight:'yawR'}[b.dataset.control]));
  const stick=$('touchStick'),knob=$('stickKnob');function moveStick(e){const r=stick.getBoundingClientRect(),x=clamp((e.clientX-r.left-r.width/2)/(r.width*.38),-1,1),y=clamp((e.clientY-r.top-r.height/2)/(r.height*.38),-1,1);touch.roll=x;touch.pitch=-y;knob.style.transform=`translate(${x*30}px,${y*30}px)`} stick.onpointerdown=e=>{stick.setPointerCapture(e.pointerId);moveStick(e)};stick.onpointermove=e=>{if(stick.hasPointerCapture(e.pointerId))moveStick(e)};stick.onpointerup=stick.onpointercancel=()=>{touch.roll=touch.pitch=0;knob.style.transform=''};
  function physics(dt){state.time+=dt;const throttleDir=(keys.KeyW||touch.up?1:0)-(keys.KeyS||touch.down?1:0);state.throttle=clamp(state.throttle+throttleDir*30*dt,0,100);const pitchIn=(keys.ArrowUp?1:0)-(keys.ArrowDown?1:0)+touch.pitch, rollIn=(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0)+touch.roll, yawIn=(keys.KeyD||touch.yawR?1:0)-(keys.KeyA||touch.yawL?1:0);state.pitch=clamp(lerp(state.pitch,pitchIn*15,.75*dt),-12,17);state.roll=clamp(lerp(state.roll,rollIn*32,1.05*dt),-40,40);state.yaw=lerp(state.yaw,yawIn*14,2*dt);const targetSpeed=Math.max(0,state.throttle*2.5-10-Math.max(0,state.pitch)*.7);state.speed=lerp(state.speed,targetSpeed,(state.altitude?.12:.075)*dt);const lift=Math.max(0,state.speed-108)*(.35+state.pitch*.065);let targetVS=state.altitude>0?lift*38-450-Math.abs(state.roll)*6:Math.max(0,lift*24-260);if(state.speed<105&&state.altitude>5)targetVS-=900;state.vSpeed=lerp(state.vSpeed,targetVS,.6*dt);state.altitude=Math.max(0,state.altitude+state.vSpeed/60*dt);state.heading=(state.heading+(state.yaw+state.roll*.13)*dt+360)%360;state.distance+=state.speed*1.6878*dt;state.fuel=Math.max(0,state.fuel-state.throttle*.0000028*dt);if(state.altitude===0&&state.vSpeed<0){if(Math.abs(state.vSpeed)>600||Math.abs(state.roll)>12){if(!state.crashed){state.crashed=true;notify('HARD LANDING · AIRCRAFT INSPECTION REQUIRED')}}else if(state.phase==='FINAL'&&!state.landed){state.landed=true;notify('TOUCHDOWN · DATTA AIR 218 AT MONTEREY')}state.vSpeed=0;state.pitch=Math.max(0,state.pitch)}if(audio){audio.osc.frequency.setTargetAtTime(42+state.throttle*.85,audio.ctx.currentTime,.1);audio.gain.gain.setTargetAtTime(sound&&!paused?.012+state.throttle*.00045:0,audio.ctx.currentTime,.1)}updatePhase()}
  function updatePhase(){let p='PREFLIGHT';if(state.speed>8)p='DEPARTURE';if(state.altitude>50)p='CLIMB';if(state.altitude>3500||state.distance>20000)p='CRUISE';if(state.distance>50000)p='DESCENT';if(state.distance>68000)p='APPROACH';if(state.distance>78000)p='FINAL';if(state.landed)p='ARRIVED';if(state.crashed)p='RESET REQUIRED';const routePct=clamp(state.distance/85000*100,0,100),r=currentRoute;if(p!==state.phase){state.phase=p;notify({DEPARTURE:`V1 · ROTATE · ${r.o}`,CLIMB:'POSITIVE RATE · GEAR UP',CRUISE:`CRUISE · ${r.w[1]} DIRECT`,DESCENT:`TOP OF DESCENT · ${r.dc}`,APPROACH:`LOCALIZER ALIVE · RUNWAY ${r.arr}`,FINAL:'LANDING CHECKLIST COMPLETE',ARRIVED:`WELCOME TO ${r.dc}`}[p]||'FLIGHT PHASE · '+p)}const data={PREFLIGHT:[`${r.o} DEPARTURE`,`${r.type} passenger service to ${r.dc}. Runway ${r.dep}; set takeoff thrust and rotate at 132 kt.`,'W / S thrust · arrows flight controls',state.throttle*.18],DEPARTURE:['TAKEOFF ROLL',`Maintain ${r.o} Runway ${r.dep} centerline. Rotate at 132 kt and establish positive climb.`,'A / D nosewheel & rudder',15+state.speed/4],CLIMB:[`CLIMB VIA ${r.w[0]}`,`Retract to climb configuration and maintain 210 kt toward ${r.w[0]}.`,`Target 2,000 ft/min · heading ${String(r.hdg).padStart(3,'0')}°`,38+state.altitude/150],CRUISE:[`${r.type} CRUISE`,`Compressed-time ${r.nm.toLocaleString()} NM sector. Track ${r.w.join(', ')} toward ${r.dc}.`,`Passengers en route · ${r.o} → ${r.d}`,55+routePct*.2],DESCENT:[`DESCEND VIA ${r.w[2]}`,`Reduce thrust and descend toward 2,000 ft for the ${r.dc} arrival.`,'Target −1,200 ft/min',76],APPROACH:[`${r.d} APPROACH`,`Configure for Runway ${r.arr}. Slow below 170 kt and descend through 1,500 ft.`,'Localizer established',88],FINAL:[`FINAL · RUNWAY ${r.arr}`,'Landing gear down. Target 138 kt and less than −600 ft/min.','Flaps 30 simulated · wings level',96],ARRIVED:['PASSENGERS ARRIVED',`Datta Air is safely on stand at ${r.dc}.`,'Press R for a new randomized flight',100],'RESET REQUIRED':['AIRCRAFT INSPECTION','Landing limits were exceeded. Reset the passenger flight to retry.','Press R to reset',100]}[p];el.title.textContent=data[0];el.text.textContent=data[1];el.hint.textContent=data[2];el.progress.style.width=clamp(data[3],2,100)+'%';el.phase.innerHTML='<i></i> '+p;el.route.style.width=routePct+'%';el.plane.style.left=routePct+'%';el.routePhase.textContent={PREFLIGHT:`GATE → RUNWAY ${r.dep}`,DEPARTURE:`${r.o} ${r.dep} DEPARTURE`,CLIMB:`${r.w[0]} CLIMB`,CRUISE:routePct<48?`DIRECT ${r.w[1]}`:`DIRECT ${r.w[2]}`,DESCENT:`${r.w[2]} ARRIVAL`,APPROACH:`${r.d} ILS ${r.arr}`,FINAL:`FINAL APPROACH ${r.arr}`,ARRIVED:`AT GATE · ${r.dc}`}[p]||'CHECKLIST';el.remaining.textContent=Math.max(0,Math.round(r.nm*(1-routePct/100))).toLocaleString()+' NM REMAINING'}
  function draw(){ctx.save();ctx.clearRect(0,0,W,H);const av=airportVisual(),speedRatio=clamp(state.speed/250,0,1),sway=Math.sin(state.time*1.45)*speedRatio*.7,cx=W/2-state.yaw*2+sway,cy=H*.48+state.pitch*H*.012-state.vSpeed*.002;ctx.translate(cx,cy);ctx.rotate(-state.roll*Math.PI/180);ctx.scale(1+speedRatio*.018,1+speedRatio*.018);const size=Math.hypot(W,H)*1.6,grad=ctx.createLinearGradient(0,-size/2,0,size/2);grad.addColorStop(0,av.colors[0]);grad.addColorStop(.38,av.colors[1]);grad.addColorStop(.49,av.colors[2]);grad.addColorStop(.505,av.colors[3]);grad.addColorStop(1,'#0c211d');ctx.fillStyle=grad;ctx.fillRect(-size,-size,size*2,size*2);ctx.fillStyle=av.dusk?'rgba(255,152,112,.55)':'rgba(255,218,161,.62)';ctx.beginPath();ctx.arc((av.side||1)*-W*.28,-H*.21,Math.max(20,W*.025),0,Math.PI*2);ctx.fill();ctx.fillStyle=av.colors[3];for(let i=0;i<9;i++){const x=-size+i*size*.25+Math.sin(i*13+av.seed)*80,h=35+Math.abs(Math.sin(i*4.7+av.seed))*120;ctx.beginPath();ctx.moveTo(x,2);ctx.lineTo(x+size*.18,-h);ctx.lineTo(x+size*.35,3);ctx.fill()}drawTerrain(ctx,size);drawAirportDetails(ctx);ctx.restore();drawClouds();drawCinematicMotion();drawHud();drawCockpitFrame()}
  function drawTerrain(g,size){const horizon=8,shift=((state.heading-currentRoute.hdg+540)%360-180)*9,travel=state.distance/760;g.save();g.beginPath();g.rect(-size,0,size*2,size);g.clip();for(let z=0;z<20;z++){const depth=((z+travel)%20)/20,y=horizon+Math.pow(depth,1.8)*H*1.15,alpha=.05+depth*.15;g.strokeStyle=`rgba(185,205,169,${alpha})`;g.lineWidth=.6+depth*1.5;g.beginPath();g.moveTo(-size,y);g.lineTo(size,y);g.stroke()}for(let x=-18;x<=18;x++){g.strokeStyle='rgba(161,189,154,.13)';g.beginPath();g.moveTo(shift+x*85,horizon);g.lineTo(shift+x*420,H*1.4);g.stroke()}const landing=state.phase==='APPROACH'||state.phase==='FINAL',departure=state.phase==='PREFLIGHT'||state.phase==='DEPARTURE',runwayCenter=shift+(landing?-state.roll*5:0),approachGain=clamp((state.distance-65000)/20000,0,1),near=landing?.22+approachGain*.78:.42;g.fillStyle='#171d20';g.beginPath();g.moveTo(runwayCenter-15,horizon);g.lineTo(runwayCenter+15,horizon);g.lineTo(runwayCenter+W*.16*near,H*.94);g.lineTo(runwayCenter-W*.16*near,H*.94);g.fill();g.strokeStyle='#e9e4d3';g.lineWidth=2;g.beginPath();g.moveTo(runwayCenter-15,horizon);g.lineTo(runwayCenter-W*.16*near,H*.94);g.moveTo(runwayCenter+15,horizon);g.lineTo(runwayCenter+W*.16*near,H*.94);g.stroke();for(let j=0;j<15;j++){const t=((j/15)+(state.distance/1500))%1,y=horizon+Math.pow(t,1.72)*H*.85,w=1+t*7;g.fillStyle=`rgba(245,242,225,${.35+t*.65})`;g.fillRect(runwayCenter-w/2,y,w,4+t*15)}for(let j=0;j<24;j++){const t=((j/24)+(state.distance/520))%1,y=horizon+Math.pow(t,1.7)*H*.86,x=W*.16*near*t;g.fillStyle=j%2?'#d7ecff':'#f3edcf';g.beginPath();g.arc(runwayCenter-x,y,1+t*2.2,0,Math.PI*2);g.arc(runwayCenter+x,y,1+t*2.2,0,Math.PI*2);g.fill()}if(!departure&&!landing){for(let i=0;i<12;i++){const cycle=((i/12)+state.distance/12000)%1,y=horizon+Math.pow(cycle,1.55)*H*.7,x=Math.sin(i*7.3+state.heading*.02)*W*.42*cycle;g.fillStyle=i%3?'#283d32':'#455a42';g.beginPath();g.moveTo(x-18*cycle,y);g.lineTo(x,y-55*cycle);g.lineTo(x+23*cycle,y);g.fill()}}g.restore()}
  function drawAirportDetails(g){const landing=state.phase==='APPROACH'||state.phase==='FINAL',departure=state.phase==='PREFLIGHT'||state.phase==='DEPARTURE',flow=departure?(state.distance%14000)/14000:landing?clamp((state.distance-65000)/20000,0,1):0,scale=landing?.75+flow*.8:.65+flow*.55,y0=H*.06+flow*H*.4;g.save();g.globalAlpha=clamp(1-state.altitude/9000,.18,1);g.fillStyle='#293137';g.beginPath();g.moveTo(-W*.42*scale,y0+35*scale);g.lineTo(-W*.08*scale,y0+12);g.lineTo(-W*.02,y0+26);g.lineTo(-W*.4*scale,y0+75*scale);g.fill();g.strokeStyle='#d9a62c';g.lineWidth=2;g.beginPath();g.moveTo(-W*.38*scale,y0+53*scale);g.quadraticCurveTo(-W*.2*scale,y0+25,-W*.04,y0+24);g.stroke();g.fillStyle='#202a2f';g.fillRect(W*.2*scale,y0-18*scale,W*.28*scale,35*scale);for(let i=0;i<7;i++){g.fillStyle=i%2?'#e3b85c':'#78b6c0';g.fillRect(W*.215*scale+i*W*.038*scale,y0-10*scale,12*scale,5*scale)}g.fillStyle='#111a20';g.fillRect(W*.25*scale,y0-45*scale,W*.045*scale,28*scale);g.fillRect(W*.36*scale,y0-36*scale,W*.035*scale,19*scale);g.fillStyle='#f4d882';for(let i=0;i<18;i++){const side=i%2?1:-1,t=((i/18)+state.distance/900)%1,yy=H*.12+Math.pow(t,1.75)*H*.7,xx=side*(18+t*W*.13*scale);g.beginPath();g.arc(xx,yy,1.2+t*1.8,0,Math.PI*2);g.fill()}g.fillStyle='#ffffff';g.font=`700 ${Math.max(12,W*.012)}px ui-monospace`;g.textAlign='center';g.fillText((landing?currentRoute.arr:currentRoute.dep).replace(/[LR]/g,''),0,H*.56+flow*H*.18);g.fillStyle='#f0e9d5';for(let k=-3;k<=3;k++){g.fillRect(k*10-3,H*.5+flow*H*.2,6,22+flow*16)}g.fillStyle='#66d4ff';for(let i=0;i<8;i++){const t=((i/8)+state.distance/1100)%1,yy=H*.55+Math.pow(t,1.5)*H*.4,xx=(i%2?1:-1)*(W*.06+t*W*.07);g.beginPath();g.arc(xx,yy,2+t,0,Math.PI*2);g.fill()}g.fillStyle='#ffd35a';g.fillRect(-W*.38*scale,y0+44*scale,52,14);g.fillStyle='#111';g.font='8px ui-monospace';g.fillText('A  ←  APRON',-W*.38*scale+26,y0+54*scale);g.restore()}
  function drawClouds(){ctx.save();for(let i=0;i<18;i++){const depth=((i/18)+state.distance/22000)%1,x=((i*251-state.heading*5+state.time*8)%(W+560))-280,y=45+depth*H*.43,r=(13+(i%5)*7)*(0.42+depth),px=x+(depth-.5)*state.roll*5,grad=ctx.createRadialGradient(px,y-r*.15,r*.15,px,y,r*3.4);grad.addColorStop(0,`rgba(255,255,255,${.11+depth*.22})`);grad.addColorStop(.45,`rgba(224,235,236,${.07+depth*.15})`);grad.addColorStop(1,'rgba(118,143,151,0)');ctx.fillStyle=grad;ctx.beginPath();ctx.ellipse(px,y,r*3.6,r*1.25,0,0,Math.PI*2);ctx.fill();for(let p=0;p<4;p++){ctx.fillStyle=`rgba(244,248,246,${.025+depth*.055})`;ctx.beginPath();ctx.arc(px-r*1.5+p*r,y-r*.25-Math.sin(p*2+i)*r*.35,r*(.65+(p%2)*.2),0,Math.PI*2);ctx.fill()}}ctx.restore()}
  function drawCinematicMotion(){const speed=clamp((state.speed-70)/180,0,1);ctx.save();const haze=ctx.createLinearGradient(0,H*.35,0,H*.72);haze.addColorStop(0,'rgba(205,223,220,0)');haze.addColorStop(1,`rgba(196,211,204,${.05+clamp(state.altitude/7000,0,.1)})`);ctx.fillStyle=haze;ctx.fillRect(0,H*.3,W,H*.45);if(speed>0){ctx.strokeStyle=`rgba(210,235,231,${speed*.1})`;ctx.lineWidth=1;for(let i=0;i<18;i++){const angle=i*2.399+state.time*.03,r=.22+((i*.173+state.distance/9000)%1)*.75,x=W/2+Math.cos(angle)*W*r,y=H*.45+Math.sin(angle)*H*r*.48,len=8+speed*28*r;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.cos(angle)*len,y+Math.sin(angle)*len*.48);ctx.stroke()}}ctx.restore()}
  function drawCockpitFrame(){ctx.save();const deck=H*.72;ctx.fillStyle='#071016';ctx.beginPath();ctx.moveTo(0,H*.55);ctx.lineTo(W*.1,deck);ctx.lineTo(W*.9,deck);ctx.lineTo(W,H*.55);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();ctx.fillStyle='#111c22';ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(W*.075,0);ctx.lineTo(W*.19,deck);ctx.lineTo(W*.1,deck);ctx.fill();ctx.beginPath();ctx.moveTo(W,0);ctx.lineTo(W*.925,0);ctx.lineTo(W*.81,deck);ctx.lineTo(W*.9,deck);ctx.fill();ctx.strokeStyle='#26363e';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(W*.075,0);ctx.lineTo(W*.19,deck);ctx.moveTo(W*.925,0);ctx.lineTo(W*.81,deck);ctx.stroke();ctx.fillStyle='#14232b';ctx.fillRect(W*.22,deck-5,W*.56,H-deck);ctx.strokeStyle='#4a5b60';ctx.lineWidth=1;for(let i=0;i<7;i++)ctx.strokeRect(W*.25+i*W*.075,deck+18,W*.06,H*.13);ctx.restore()}
  function drawHud(){ctx.save();ctx.strokeStyle='rgba(88,235,212,.42)';ctx.fillStyle='rgba(88,235,212,.72)';ctx.lineWidth=1;ctx.font='9px ui-monospace';const cy=H*.45-state.pitch*8;for(let p=-20;p<=20;p+=5){if(!p)continue;const y=cy+p*8,w=p%10===0?50:25;ctx.beginPath();ctx.moveTo(W/2-w,y);ctx.lineTo(W/2-8,y);ctx.moveTo(W/2+8,y);ctx.lineTo(W/2+w,y);ctx.stroke();if(p%10===0){ctx.fillText(String(-p),W/2+w+5,y+3);ctx.fillText(String(-p),W/2-w-20,y+3)}}ctx.restore()}
  function ui(){el.speed.textContent=Math.round(state.speed).toString().padStart(3,'0');el.alt.textContent=Math.round(state.altitude).toString().padStart(4,'0');const hd=Math.round(state.heading)%360;el.heading.textContent=hd.toString().padStart(3,'0')+'°';el.direction.textContent=['N','NE','E','SE','S','SW','W','NW'][Math.round(hd/45)%8];const v=Math.round(state.vSpeed/10)*10;el.vspeed.textContent=(v>=0?'+':'−')+Math.abs(v).toString().padStart(3,'0');el.throttle.textContent=Math.round(state.throttle).toString().padStart(2,'0');el.speedBar.style.width=clamp(state.speed/260*100,0,100)+'%';el.altBar.style.width=clamp(state.altitude/7000*100,0,100)+'%';el.vsiBar.style.width=clamp(50+state.vSpeed/40,0,100)+'%';el.throttleBar.style.width=state.throttle+'%';el.n1.textContent=(22+state.throttle*.76).toFixed(1);const landing=state.phase==='APPROACH'||state.phase==='FINAL';el.flaps.textContent=landing?(state.phase==='FINAL'?30:15):(state.altitude<100?5:0);el.gear.textContent=state.altitude<80||landing?'DOWN':'UP';el.gearLight.textContent=state.altitude<80||landing?'●':'○';el.fuel.textContent=state.fuel.toFixed(1)}
  function loop(now){const dt=Math.min(.04,(now-last)/1000);last=now;fpsSmooth=lerp(fpsSmooth,1/Math.max(dt,.001),.05);if(!paused)physics(dt);draw();ui();el.fps.textContent=Math.round(fpsSmooth)+' FPS';requestAnimationFrame(loop)}chooseRoute();updatePhase();requestAnimationFrame(loop);
  const drawGenericTerrain=drawTerrain;
  drawTerrain=function(g,size){drawGenericTerrain(g,size);drawSurfaceDetail(g)};
  function drawSurfaceDetail(g){const landing=state.phase==='APPROACH'||state.phase==='FINAL',motion=state.distance/430;g.save();const mist=g.createLinearGradient(0,0,0,H*.32);mist.addColorStop(0,'rgba(225,235,231,.19)');mist.addColorStop(1,'rgba(225,235,231,0)');g.fillStyle=mist;g.fillRect(-W,0,W*2,H*.34);g.globalAlpha=.24;g.strokeStyle='#080b0d';g.lineWidth=1;for(let i=0;i<34;i++){const t=((i/34)+motion*.037)%1,y=H*.04+Math.pow(t,1.72)*H*.84,x=((i*97+airportVisual().seed*13)%Math.max(1,W*.24))-W*.12,len=2+t*28;g.beginPath();g.moveTo(x-len,y);g.lineTo(x+len,y+len*.08);g.stroke()}g.globalAlpha=landing?.38:.2;g.strokeStyle='#090b0d';g.lineWidth=2;for(const side of [-1,1]){g.beginPath();g.moveTo(side*5,H*.15);g.quadraticCurveTo(side*18,H*.52,side*W*.035,H*.92);g.stroke()}g.globalAlpha=.22;for(let i=0;i<22;i++){const t=((i/22)+motion*.08)%1,y=H*.18+Math.pow(t,1.6)*H*.67,w=1+t*4;g.fillStyle=i%3?'#c8d0c5':'#8a8e82';g.fillRect(((i*71)%Math.max(1,W*.18))-W*.09,y,w,w*.55)}g.restore()}
  const drawGenericAirport=drawAirportDetails;
  drawAirportDetails=function(g){drawLocationContext(g,airportVisual());drawGenericAirport(g)};
  function drawLocationContext(g,av){g.save();g.globalAlpha=clamp(1-state.altitude/11000,.2,.9);const h=H*.1;if(['coast','bay','harbor','tropical'].includes(av.terrain)){g.fillStyle=av.terrain==='tropical'?'#337d79':'#315f72';g.fillRect(-W*.8,h+35,W*1.6,H*.18);g.strokeStyle='rgba(210,238,235,.3)';for(let i=0;i<7;i++){g.beginPath();g.moveTo(-W*.7,h+45+i*13);g.lineTo(W*.7,h+45+i*13);g.stroke()}}if(av.terrain==='mountain'||av.terrain==='plateau'){g.fillStyle=av.terrain==='mountain'?'#4b5260':'#59654d';g.beginPath();g.moveTo(-W*.75,h+40);for(let i=0;i<11;i++){const x=-W*.75+i*W*.15,y=h-(20+((av.seed+i*37)%75));g.lineTo(x,y)}g.lineTo(W*.8,h+80);g.fill()}if(av.terrain==='desert'){g.fillStyle='#98764f';g.fillRect(-W*.8,h,W*1.6,H*.2);g.fillStyle='#544c47';for(let i=0;i<9;i++){const x=(-W*.55+i*W*.13)*av.side,ht=18+((av.seed+i*19)%80);g.fillRect(x,h-ht,18+(i%3)*8,ht)}}if(av.terrain==='urban'||av.terrain==='bay'||av.terrain==='harbor'){g.fillStyle='#28343b';for(let i=0;i<16;i++){const x=-W*.65+i*W*.085,ht=12+((av.seed+i*23)%55);g.fillRect(x,h-ht,14+(i%4)*6,ht)}}if(av.terrain==='flat'){g.strokeStyle='rgba(206,191,138,.25)';for(let i=-7;i<8;i++){g.beginPath();g.moveTo(i*W*.09,h);g.lineTo(i*W*.24,H*.5);g.stroke()}}g.strokeStyle='#687278';g.lineWidth=5;if(av.layout===1){g.beginPath();g.moveTo(-W*.42,h+90);g.lineTo(W*.38,h+170);g.stroke()}else if(av.layout===2){g.beginPath();g.moveTo(-W*.5,h+150);g.lineTo(W*.48,h+150);g.stroke()}g.fillStyle='#ffd65b';g.fillRect(av.side*W*.31-34,h+74,68,15);g.fillStyle='#111';g.font='8px ui-monospace';g.textAlign='center';g.fillText(`${av.code} · TWY ${String.fromCharCode(65+av.layout)}`,av.side*W*.31,h+85);g.restore()}
})();
