(() => {
  'use strict';
  const canvas = document.getElementById('world'), ctx = canvas.getContext('2d');
  const $ = id => document.getElementById(id);
  const el = {speed:$('speed'),alt:$('altitude'),heading:$('heading'),direction:$('direction'),vspeed:$('vspeed'),throttle:$('throttle'),speedBar:$('speedBar'),altBar:$('altBar'),vsiBar:$('vsiBar'),throttleBar:$('throttleBar'),phase:$('phasePill'),title:$('missionTitle'),text:$('missionText'),progress:$('missionProgress'),hint:$('hint'),message:$('message'),pause:$('pauseOverlay'),fps:$('fps')};
  let W=0,H=0,dpr=1,last=performance.now(),paused=false,sound=false,audio=null,msgTimer=0,fpsSmooth=60;
  const keys={}, touch={pitch:0,roll:0,yaw:0,up:false,down:false};
  const state={throttle:0,speed:0,altitude:0,heading:0,pitch:0,roll:0,yaw:0,vSpeed:0,distance:0,phase:'PREFLIGHT',landed:false,crashed:false,time:0};
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), lerp=(a,b,t)=>a+(b-a)*t;
  function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)} addEventListener('resize',resize);resize();
  addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyS','KeyA','KeyD','Space','KeyP','KeyR'].includes(e.code))e.preventDefault();keys[e.code]=true;if((e.code==='Space'||e.code==='KeyP')&&!e.repeat)togglePause();if(e.code==='KeyR'&&!e.repeat)reset()});
  addEventListener('keyup',e=>keys[e.code]=false);
  function notify(t){el.message.textContent=t;el.message.classList.add('show');clearTimeout(msgTimer);msgTimer=setTimeout(()=>el.message.classList.remove('show'),2200)}
  function reset(){Object.assign(state,{throttle:0,speed:0,altitude:0,heading:0,pitch:0,roll:0,yaw:0,vSpeed:0,distance:0,phase:'PREFLIGHT',landed:false,crashed:false,time:0});paused=false;el.pause.classList.remove('show');notify('AIRCRAFT RESET · RUNWAY 28')}
  function togglePause(){paused=!paused;el.pause.classList.toggle('show',paused);$('pauseBtn').textContent=paused?'RESUME':'PAUSE';if(audio)audio.gain.gain.setTargetAtTime(paused?0:state.throttle*.045,audio.ctx.currentTime,.08)}
  $('pauseBtn').onclick=togglePause;$('resumeBtn').onclick=togglePause;$('resetBtn').onclick=reset;
  $('helpToggle').onclick=()=>{const c=document.querySelector('.controls-card');c.classList.toggle('hidden');$('helpToggle').textContent=c.classList.contains('hidden')?'SHOW CONTROLS':'HIDE CONTROLS'};
  $('soundBtn').onclick=()=>{sound=!sound;$('soundBtn').textContent=sound?'SOUND ON':'SOUND OFF';if(sound&&!audio){const ac=new (window.AudioContext||window.webkitAudioContext)(),osc=ac.createOscillator(),gain=ac.createGain(),filter=ac.createBiquadFilter();osc.type='sawtooth';osc.frequency.value=55;filter.type='lowpass';filter.frequency.value=180;gain.gain.value=0;osc.connect(filter).connect(gain).connect(ac.destination);osc.start();audio={ctx:ac,osc,gain}}};
  function bindHold(btn,name){const set=v=>{touch[name]=v;btn.classList.toggle('active',v)};btn.addEventListener('pointerdown',e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);set(true)});btn.addEventListener('pointerup',()=>set(false));btn.addEventListener('pointercancel',()=>set(false))}
  document.querySelectorAll('[data-control]').forEach(b=>bindHold(b,{throttleUp:'up',throttleDown:'down',yawLeft:'yawL',yawRight:'yawR'}[b.dataset.control]));
  const stick=$('touchStick'),knob=$('stickKnob');function moveStick(e){const r=stick.getBoundingClientRect(),x=clamp((e.clientX-r.left-r.width/2)/(r.width*.38),-1,1),y=clamp((e.clientY-r.top-r.height/2)/(r.height*.38),-1,1);touch.roll=x;touch.pitch=-y;knob.style.transform=`translate(${x*30}px,${y*30}px)`} stick.onpointerdown=e=>{stick.setPointerCapture(e.pointerId);moveStick(e)};stick.onpointermove=e=>{if(stick.hasPointerCapture(e.pointerId))moveStick(e)};stick.onpointerup=stick.onpointercancel=()=>{touch.roll=touch.pitch=0;knob.style.transform=''};
  function physics(dt){state.time+=dt;const throttleDir=(keys.KeyW||touch.up?1:0)-(keys.KeyS||touch.down?1:0);state.throttle=clamp(state.throttle+throttleDir*35*dt,0,100);const pitchIn=(keys.ArrowUp?1:0)-(keys.ArrowDown?1:0)+touch.pitch, rollIn=(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0)+touch.roll, yawIn=(keys.KeyD||touch.yawR?1:0)-(keys.KeyA||touch.yawL?1:0);state.pitch=clamp(lerp(state.pitch,pitchIn*18,.9*dt),-16,20);state.roll=clamp(lerp(state.roll,rollIn*38,1.2*dt),-48,48);state.yaw=lerp(state.yaw,yawIn*18,2*dt);const targetSpeed=Math.max(0,state.throttle*1.72-8-Math.max(0,state.pitch)*.45);state.speed=lerp(state.speed,targetSpeed,(state.altitude? .14:.09)*dt);const lift=Math.max(0,state.speed-72)*(.5+state.pitch*.075);let targetVS=state.altitude>0?lift*42-520-Math.abs(state.roll)*6:Math.max(0,lift*28-350);if(state.speed<58&&state.altitude>5)targetVS-=700;state.vSpeed=lerp(state.vSpeed,targetVS,.7*dt);state.altitude=Math.max(0,state.altitude+state.vSpeed/60*dt);state.heading=(state.heading+(state.yaw+state.roll*.16)*dt+360)%360;state.distance+=state.speed*1.6878*dt; if(state.altitude===0&&state.vSpeed<0){if(Math.abs(state.vSpeed)>650||Math.abs(state.roll)>18){if(!state.crashed){state.crashed=true;notify('HARD LANDING · AIRCRAFT DAMAGED')}}else if(state.phase==='APPROACH'&&!state.landed){state.landed=true;notify('TOUCHDOWN · EXCELLENT WORK')}state.vSpeed=0;state.pitch=Math.max(0,state.pitch)} if(audio){audio.osc.frequency.setTargetAtTime(45+state.throttle*.7,audio.ctx.currentTime,.1);audio.gain.gain.setTargetAtTime(sound&&!paused?.012+state.throttle*.00045:0,audio.ctx.currentTime,.1)} updatePhase()}
  function updatePhase(){let p='PREFLIGHT';if(state.speed>5)p='TAKEOFF';if(state.altitude>35)p='CLIMB';if(state.altitude>850)p='CRUISE';if(state.distance>32000)p='APPROACH';if(state.landed)p='LANDED';if(state.crashed)p='RESET REQUIRED';if(p!==state.phase){state.phase=p;notify(p==='CLIMB'?'POSITIVE RATE · CLIMB TO 1,200 FT':p==='CRUISE'?'CRUISE ALTITUDE · FOLLOW COASTLINE':p==='APPROACH'?'RUNWAY AHEAD · DESCEND BELOW 500 FT':p==='LANDED'?'FLIGHT COMPLETE':'FLIGHT PHASE · '+p)}const data={PREFLIGHT:['CLEAR FOR TAKEOFF','Advance throttle, hold centerline, then ease the nose up above 90 kt.','W throttle up · ↑ pitch up',state.throttle*.25],TAKEOFF:['TAKEOFF ROLL','Maintain centerline. Rotate smoothly as airspeed passes 90 kt.','A / D rudder · ↑ rotate',25+state.speed/7],CLIMB:['CLIMB TO 1,200 FT','Keep the wings level and settle near 110 kt.','Target +800 ft/min',45+state.altitude/60],CRUISE:['COASTAL TRANSIT','Hold 1,200 ft and follow heading 280° toward Northstar Field.','Begin descent after the guidance alert',72+(state.distance-8000)/1400],APPROACH:['LANDING APPROACH','Reduce power. Aim for 65–85 kt and less than −500 ft/min.','Runway 28 · heading 280°',88+Math.min(11,(state.distance-32000)/1800)],LANDED:['FLIGHT COMPLETE','Welcome to Northstar Field. A smooth arrival.','Press R to fly again',100],'RESET REQUIRED':['HARD LANDING','The aircraft exceeded safe landing limits. Reset to try again.','Press R to reset',100]}[p];el.title.textContent=data[0];el.text.textContent=data[1];el.hint.textContent=data[2];el.progress.style.width=clamp(data[3],2,100)+'%';el.phase.innerHTML='<i></i> '+p}
  function draw(){ctx.save();ctx.clearRect(0,0,W,H);const cx=W/2,cy=H*.48+state.pitch*H*.012;ctx.translate(cx,cy);ctx.rotate(-state.roll*Math.PI/180);const size=Math.hypot(W,H)*1.6,grad=ctx.createLinearGradient(0,-size/2,0,size/2);grad.addColorStop(0,'#456d7b');grad.addColorStop(.36,'#9bb3b0');grad.addColorStop(.49,'#e7c79b');grad.addColorStop(.505,'#6a7660');grad.addColorStop(1,'#152b26');ctx.fillStyle=grad;ctx.fillRect(-size,-size,size*2,size*2);ctx.fillStyle='rgba(255,208,142,.7)';ctx.beginPath();ctx.arc(-W*.28,-H*.21,Math.max(20,W*.025),0,Math.PI*2);ctx.fill();ctx.fillStyle='#445b4b';for(let i=0;i<9;i++){const x=-size+i*size*.25+Math.sin(i*13)*80,h=40+Math.abs(Math.sin(i*4.7))*100;ctx.beginPath();ctx.moveTo(x,2);ctx.lineTo(x+size*.18,-h);ctx.lineTo(x+size*.35,3);ctx.fill()}drawTerrain(ctx,size);ctx.restore();drawClouds();drawHud();}
  function drawTerrain(g,size){const horizon=8,shift=((state.heading-280+540)%360-180)*9;g.save();g.beginPath();g.rect(-size,0,size*2,size);g.clip();for(let z=1;z<18;z++){const depth=z/18,y=horizon+Math.pow(depth,1.8)*H*1.15,alpha=.06+depth*.08;g.strokeStyle=`rgba(185,205,169,${alpha})`;g.lineWidth=1;g.beginPath();g.moveTo(-size,y);g.lineTo(size,y);g.stroke()}for(let x=-18;x<=18;x++){g.strokeStyle='rgba(161,189,154,.13)';g.beginPath();g.moveTo(shift+x*85,horizon);g.lineTo(shift+x*420,H*1.4);g.stroke()}const runwayCenter=shift+(state.phase==='APPROACH'?-state.roll*5:0),near=state.phase==='APPROACH'?Math.max(.25,1-(state.distance-32000)/20000):.16;g.fillStyle='#1a2323';g.beginPath();g.moveTo(runwayCenter-16,horizon);g.lineTo(runwayCenter+16,horizon);g.lineTo(runwayCenter+W*.16*near,H*.9);g.lineTo(runwayCenter-W*.16*near,H*.9);g.fill();g.strokeStyle='#e5e0c5';g.lineWidth=2;for(let j=0;j<9;j++){const t=j/9,y=horizon+Math.pow(t,1.8)*H*.8,w=2+t*5;g.beginPath();g.moveTo(runwayCenter-w,y);g.lineTo(runwayCenter+w,y);g.stroke()}g.restore()}
  function drawClouds(){ctx.save();ctx.globalAlpha=.11;ctx.fillStyle='#fff';for(let i=0;i<12;i++){const x=(i*247-state.heading*4+state.time*2)%(W+300)-150,y=90+(i*67)%Math.max(120,H*.32),r=18+(i%4)*9;ctx.beginPath();ctx.ellipse(x,y,r*3,r,0,0,Math.PI*2);ctx.fill()}ctx.restore()}
  function drawHud(){ctx.save();ctx.strokeStyle='rgba(88,235,212,.42)';ctx.fillStyle='rgba(88,235,212,.72)';ctx.lineWidth=1;ctx.font='9px ui-monospace';const cy=H*.45-state.pitch*8;for(let p=-20;p<=20;p+=5){if(!p)continue;const y=cy+p*8,w=p%10===0?50:25;ctx.beginPath();ctx.moveTo(W/2-w,y);ctx.lineTo(W/2-8,y);ctx.moveTo(W/2+8,y);ctx.lineTo(W/2+w,y);ctx.stroke();if(p%10===0){ctx.fillText(String(-p),W/2+w+5,y+3);ctx.fillText(String(-p),W/2-w-20,y+3)}}ctx.restore()}
  function ui(){el.speed.textContent=Math.round(state.speed).toString().padStart(3,'0');el.alt.textContent=Math.round(state.altitude).toString().padStart(4,'0');const hd=Math.round(state.heading)%360;el.heading.textContent=hd.toString().padStart(3,'0')+'°';el.direction.textContent=['N','NE','E','SE','S','SW','W','NW'][Math.round(hd/45)%8];const v=Math.round(state.vSpeed/10)*10;el.vspeed.textContent=(v>=0?'+':'−')+Math.abs(v).toString().padStart(3,'0');el.throttle.textContent=Math.round(state.throttle).toString().padStart(2,'0');el.speedBar.style.width=clamp(state.speed/180*100,0,100)+'%';el.altBar.style.width=clamp(state.altitude/1800*100,0,100)+'%';el.vsiBar.style.width=clamp(50+state.vSpeed/30,0,100)+'%';el.throttleBar.style.width=state.throttle+'%'}
  function loop(now){const dt=Math.min(.04,(now-last)/1000);last=now;fpsSmooth=lerp(fpsSmooth,1/Math.max(dt,.001),.05);if(!paused)physics(dt);draw();ui();el.fps.textContent=Math.round(fpsSmooth)+' FPS';requestAnimationFrame(loop)} updatePhase();requestAnimationFrame(loop);
})();
